### ISSUE TITLE
4th link in homework01/homework_differentiation.ipynb is broken

### ISSUE THREAD

**Issue by Pastafarianist** [yandexdataschool/Practical_DL#10]
It leads to http://research.microsoft.com/en-us/um/people/cmbishop/prml/index.htm which redirects to https://www.microsoft.com/en-us/research/people/cmbishop/?from=http%3A%2F%2Fresearch.microsoft.com%2Fen-us%2Fum%2Fpeople%2Fcmbishop%2Fprml%2Findex.htm, which is probably not intended.

**Comment by simflin** [comment]
Indeed. There was a link to the book of Cristopher Bishop "Pattern Recognition and Machine Learning". I will fix the link latter. You can find the book here http://users.isr.ist.utl.pt/~wurmd/Livros/school/Bishop%20-%20Pattern%20Recognition%20And%20Machine%20Learning%20-%20Springer%20%202006.pdf
