### ISSUE TITLE
Is the formula correct in homework 1 ex 4 ?

### ISSUE THREAD

**Issue by s0lucien** [yandexdataschool/Practical_DL#13]
There may be an error in ex 4's statement . I  believe it should be ||X||_F^2 = tr(...) instead . You also use the Frobenius norm later in the second approach.

In exercise 4. you say: 

![image](https://user-images.githubusercontent.com/5057738/37560992-92130fee-2a43-11e8-99e3-655518aee7b8.png)

The fact is not too obvious as the 2-norm is Jose Nocedal's Numerical Optimization book as:

![image](https://user-images.githubusercontent.com/5057738/37560975-2bd698ae-2a43-11e8-93b7-5eb0394f6b7d.png)

I have found the following readings useful regarding this issue *but was not clarified -  the rabbit hole runs deep* :
- Pedersen and Pedersen - The Matrix Cookbook : (262) page 30
- [Stackoverflow](https://math.stackexchange.com/questions/546155/proof-that-the-trace-of-a-matrix-is-the-sum-of-its-eigenvalues) and [mathpages](http://www.mathpages.com/home/kmath128.htm) with proofs about the characteristic polynomial

**Comment by DmitryUlyanov** [comment]
Hi, yes, it is a typo, it is Frobenius norm, not 2.
