### ISSUE TITLE
Can you put lecture slides/notes here as well to make repo complete?

### ISSUE THREAD

**Issue by ilivans** [yandexdataschool/Practical_DL#8]

**Comment by justheuristic** [comment]
You can find full version with slides for previous course in fall17 branch:
https://github.com/yandexdataschool/Practical_DL/tree/fall17/week0
(see readme at the end)
Those are HSE sides. If you meant "can we update slides with YSDA track" please clarify.

**Comment by ilivans** [comment]
Sure, I meant recent YSDA lectures materials.
